# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c70e71469812107cbd90a28fdd4a2951d5dd7a85187b365bfe4f2a312855c29ed29280dd3292d973c9125a6cf89b4ec476d652627d9dd456355db03b57839af

test:
  secret_key_base: a1ad54b1eac802f1557fdf669b57273b51cc43d6824f6b49d552951980f0eb9e3c7b3e83c1c302d5939f110442287dadb128c6df7923c084b0632b2eb01b5844

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
